services:
  content-proxy-dev-db:
    image: postgres:16-alpine
    container_name: content-proxy-dev-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content-proxy_dev
    ports:
      - '5433:5432'
    volumes:
      - content-proxy-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  content-proxy-test-db:
    image: postgres:16-alpine
    container_name: content-proxy-test-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: content-proxy_test
    ports:
      - '5434:5432'
    volumes:
      - content-proxy-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  content-proxy-dev-data:
  content-proxy-test-data:
